name: demo-action

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Your Step Name Here
        run: echo "Hello, GitHub Actions!"
